### ISSUE TITLE
UnhandledPromiseRejectionWarning: FetchError

### ISSUE THREAD

**Issue by shbalaku** [PagerDuty/pdjs#110]
FetchError from node-fetch are not handled in the following scenario:

pd.all('/incidents', {data: ... })
     .then(...)
     .catch(...)

**Comment by shbalaku** [comment]
no catch statement here: https://github.com/PagerDuty/pdjs/blob/46c2595df5a3fff81a6352cc4cfa6a5d20c627a2/src/common.ts#L48

**Comment by bzmw** [comment]
Hey there.
Can you provide a full example for this error so that we can effectively recreate the issue?

**Comment by shbalaku** [comment]
```
pd.all('/incidents', {
      data: {
        "service_ids[]": service_ids,
        "since": d_since.toISOString(),
        "sort_by": "created_at:desc,urgency:desc",
        "statuses[]": ["triggered", "acknowledged"],
        "total": true,
        "until": d_until.toISOString()
      }
    })
    .then( (response) => {
      if (response.status == 200) {
        const data = response.data;
        resolve(data);
      } else {
        reject(new Error(response.status + " " + response.statusText));
      }
    })
    .catch( (error) => {
      reject(error);
    });
 ```
    
This is the code I am using in a node environment. In a situation when the network times out, I get the following UnhandledPromiseRejectionWarning:

```
FetchError: request to https://api.pagerduty.com/incidents?service_ids%5B%5D=PES5P0Z&service_ids%5B%5D=PW0GKF4&since=2020-12-01T14%3A25%3A43.921Z&sort_by=created_at%3Adesc%2Curgency%3Adesc&statuses%5B%5D=triggered&statuses%5B%5D=acknowledged&total=true&until=2021-03-01T14%3A25%3A43.921Z&limit=25&offset=25 failed, reason: connect ETIMEDOUT 44.232.118.253:443
    at ClientRequest.<anonymous> (/var/www/singlepane/server/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

**Comment by bzmw** [comment]
Thanks this is helpful I'll have a look within the next couple weeks to add a catch statement for the timeout.
